version: '3.8'

services:
  fraud-app:
    build:
      context: .
    container_name: fraud-app

    volumes:
      - ./outputs:/outputs
      - ./data:/data

    working_dir: /app

    user: "${UID:-1000}:${GID:-1000}"

    restart: "no"
    #command: python testfile.py


