version: '3.8'

services:
  fraud-app:
    build:
      context: .
    #container_name: fraud-app

    environment:
      DB_HOST: db
      DB_PORT: 5432 
      # POSTGRES_PASSWORD: ${DB_PWD}
      # POSTGRES_USER: ${DB_USR_NAME}
      # POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "fraud_db"

    volumes:
      - ./outputs:/outputs
      - ./data:/data

    working_dir: /app

    env_file:
      - .env

    user: "${UID:-1000}:${GID:-1000}" # no root

    restart: "no"

    depends_on:
      db:
        condition: service_healthy
    #command: python testfile.py

  db:
    image: postgres:16
    container_name: sqldb
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_USER: ${DB_USR_NAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USR_NAME}"] # should work
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # bind mount
      # init.sql??
    
#  for not bind mount
# volumes:
#   postgres_data:
